### ISSUE TITLE
Error while reading SeedDataset

### ISSUE THREAD

**Issue by flehn** [torcheeg/torcheeg#53] opened 2023-08-29 10:18 UTC
A few weeks ago I had no issues, however suddenly it is not possible to create a dataset with SeedDataset() Class anymore. 
It results in the ValueError: invalid literal for int() with base 10: ''
Please find attached a screenshot of the full error message.

I think it is related to the new parallel method. 

<img width="413" alt="Screenshot 2023-08-29 at 11 47 00" src="https://github.com/torcheeg/torcheeg/assets/51052287/e0b2f3fc-b45f-413c-a0e4-db224d227119">

**Comment by tczhangzhi** [comment] 2023-08-29 16:51
The error you've encountered appears to be related to the recent version update. I can suggest two solutions to address this:

Update to the latest version, TorchEEGv1.1.0. However, make sure to delete the old dataset cache using the command:

```
rm -rf non_augmented_train
```

If you prefer, you can also revert to the older version, TorchEEGv1.0.11, by running:

```
pip install torcheeg==1.0.11
```

If you're working on a research project and want to ensure reproducibility, you can specify the version in your requirements.txt as:

```
torcheeg==1.0.11
# or torcheeg==1.1.0
```

In fact, we highly recommend using torcheeg1.1.0. Not only does it enhance dataset loading speeds and ensure cross-platform compatibility, but it also comes with built-in contrastive learning trainers, such as: [SimCLRTrainer](https://torcheeg.readthedocs.io/en/latest/generated/torcheeg.trainers.SimCLRTrainer.html#torcheeg.trainers.SimCLRTrainer).

Thank you for your support.

**Comment by tczhangzhi** [comment] 2023-11-09 08:27
It looks like this issue has been resolved, so I'll close it. If you have other questions, feel free to reopen it.

**Closed by tczhangzhi** 2023-11-09 08:27 UTC

**Comment by SHAOHUASONGgit** [comment] 2024-08-03 03:59
> The error you've encountered appears to be related to the recent version update. I can suggest two solutions to address this:
> 
> Update to the latest version, TorchEEGv1.1.0. However, make sure to delete the old dataset cache using the command:
> 
> ```
> rm -rf non_augmented_train
> ```
> 
> If you prefer, you can also revert to the older version, TorchEEGv1.0.11, by running:
> 
> ```
> pip install torcheeg==1.0.11
> ```
> 
> If you're working on a research project and want to ensure reproducibility, you can specify the version in your requirements.txt as:
> 
> ```
> torcheeg==1.0.11
> # or torcheeg==1.1.0
> ```
> 
> In fact, we highly recommend using torcheeg1.1.0. Not only does it enhance dataset loading speeds and ensure cross-platform compatibility, but it also comes with built-in contrastive learning trainers, such as: [SimCLRTrainer](https://torcheeg.readthedocs.io/en/latest/generated/torcheeg.trainers.SimCLRTrainer.html#torcheeg.trainers.SimCLRTrainer).
> 
> Thank you for your support.

Well I got this error when I delete processed data and rerun my script, and it seems that the script get a None when getting sub id. So I think the script may read in a hidden doc or file but treat it as a record, then I ls the doc and delete .ipynb_checkpoints and rerun, error disappears :)
